### ISSUE TITLE
index iterator in PayloadFormatter

### ISSUE THREAD

**Issue by Kilvoctu** [gingivere0/dalebot#2]
Hello,

I'm coming from [the discussion thread](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/2108) on AUTOMATIC1111's repo, and I've been implementing your amazing PayloadFormatter into my fork of harubaru's bot (I like slash commands).

Looking through PayloadFormatter.py, I noticed something odd at line 110. Here's a snippet:
```
elif labelvaluetuplelist[i][0] == "Negative Prompt":
    data_holder.exclude_ind = i
    print(f'negprompt: {str(i)}')
elif labelvaluetuplelist[i][0] == "Sampling Steps":
    data_holder.exclude_ind = i
    print(f'samples: {str(i)}')
```

`Sampling Steps` is storing value into the same index as `Negative Prompt`? Referencing the DataHolder class, I think line 110 should be `data_holder.sample_ind = i` instead, right? Not sure if I'm missing something.

**Comment by gingivere0** [comment]
Yep that was a mistype! Thanks for pointing that out, should be fixed now. I'm glad you're able to use the class!

**Comment by Kilvoctu** [comment]
I know this is a different issue, but I caught a behavior in which `exclude_ind` is not being assigned correctly to the data holder. 

You can test by going to DataHolder class and initializing `self.exclude_ind` to 0 or any other number, then see `do_format` pass over it unchanged.

In that snippet of code above, line 108:
`elif labelvaluetuplelist[i][0] == "Negative Prompt":`
the word "Prompt" should be lowercase as seen in the webui config.
`elif labelvaluetuplelist[i][0] == "Negative prompt":`
I tried some fancy dynamic solutions the fix the issue with the case sensitive, but couldn't get anything else to work.

Also, thanks again for that class! You can check out my fork if you want to see how I implement it; more or less drag and drop 😄

**Comment by gingivere0** [comment]
Another typo, just pushed a fix for it! I'm sure there are plenty more in the project 😂
