### ISSUE TITLE
Feature request: Adding support (optional) for authentication with gradio.app credentials

### ISSUE THREAD

**Issue by Darkflo264** [gingivere0/dalebot#3]
Hello gingivere0!

Situation:
Your bot is working very well for discord integration. But my situation is as follows:
I want to give some guys in our Discord access to use the SD-UI by bot, which is working well.
I also want to give some special guys access to the full SD-Web-UI.
But i do not want everyone in the Discord to have full access.
Also do i not want to publish my local sd-web-ui without auth by credentials at gradio.app.

The problem here is, even if i am using 127.0.0.1:7860, i need to authenticate witch credentials i configured when starting the webui-user.bat

It would be awesome if there would be option to uncomment or something like that, to include and pass credentials to the url.

I am currently playing arround to include something like this, but did not work so well yet:

`# Making a get request`
`response = requests.get('http://127.0.0.1:7860',`
            `auth = HTTPBasicAuth('username', 'password'))`

To prevent cleartext credentials i think they could be stored in the .env file as well?

Might be a very specific feature-request but i am almost sure i am thinking way to complicated and there is some easy solution for this (or none at all)

Thank you again and have a nice day!

Greetings

Darkflo

**Comment by Darkflo264** [comment]
Addition:
Your inplementation of the sampler parameter works fine - except the "DPM adaptive" sampler for me.

**Comment by gingivere0** [comment]
Hey!

So you want some approved users to be able to use dalebot? I can't do anything to restrict access to the SD-web-ui, but I think I can restrict access to dalebot for only approved users if that's what you're looking for

**Comment by Darkflo264** [comment]
Hey!  
Sorry, maybe i wrote this a confusing way!
Its already possible to add additional starting parameters in the webui-user.bat from the sd-web-ui.
By default its only accessable by 127.0.0.1. This works without problem in combination with your bot.
--listen      Makes it use 0.0.0.0 and available for the local LAN. This works also well.
--share      Will share it by   gradio.app  which can be accessed from everywhere.  The contra of this is, the access is "open". Everyone can use it. But, when the following parameter for startup is added as well:
--gradio-auth username:password         The sd-web-ui is shared to the internet, accessable for everyone. But before able to use it, they get a authentication website asking for username and password. (these can be defined by webui-user.bat)
This works very well for the sd-web-ui.


<img width="588" alt="webui" src="https://user-images.githubusercontent.com/114169154/196051182-436ba725-e0c3-4054-94b6-b1e24936e81e.png">


<img width="159" alt="gradio_login" src="https://user-images.githubusercontent.com/114169154/196050750-695b701a-c675-46d5-84b6-a558a5eff030.png">


BUT, as soon as i am sharing it to the internet (to the approved users i want be able to use the full web-ui) the bot is not working anymore. 
The problem here is, even if i am accessing the sd-web-ui by 127.0.0.1, i need to authenticate for access.
Of course, the bot can´t pass its request to the web-ui now because he would have to authenticate at first as well.

So my question is, it it possible to make the bot access 127.0.0.1 and doing a "login" by passing defined authentification credentials there?

I am not sure if this might be directely possible with
`url = "http://127.0.0.1:7860/api/predict"`
or if a previous "contact" to authenticate is needed. The behavior in browsers is, once you are logged in, the credentials are stored (in a cookie i think) and no additional authentication is required, even after closing and re-open url in your browser.
A re-authentication is needed as soon as the sd-web-ui is restarted and shared with a different url.


This is a very, very specific request :)    if this is not possible or possible a easy way, do not worry. Maybe i will experiment a bit more myself, but i really do suck at python. (i am not even a programmer)
But it would be the "non-plus-ultra" if both would work.

Keep going, your bot is truely awesome!

**Comment by gingivere0** [comment]
Ok I think I've got it! Try pulling my latest update. You need to set your username and password in the .env file. You can see an example picture in the README. Let me know if everything works for you

**Comment by Darkflo264** [comment]
Hey!
Sorry, i was quite busy. I pulled your update and it seems to work really well!  That’s fantastic!  Thank you very much. 
I wish I could do more myself. I’m a it guy but lack programming experience. Do you have any recommendations for resources or something when I want to start and get into Python coding?

**Comment by gingivere0** [comment]
I'm glad it's working! I mainly studied Java in school with a little bit of Python basics. All of the other Python knowledge comes from me trying to do something, googling how, and then trial-and-error until I can figure out how to fix whatever the problem is. I don't really have a resource that I've used to learn the language, which is why I'm sure my code looks super weird to someone who's actually good at Python.
