### ISSUE TITLE
Bug report: Samplers with "space" not working

### ISSUE THREAD

**Issue by Darkflo264** [gingivere0/dalebot#4]
hey!
Your inplementation of the sampler parameter works fine - except the "DPM adaptive" and other sampler with a space in name.

When i, for example, do the prompt you have included in your "!dale help" message,  "!dale firetruck conform=20 num=4 samples=15 res=832x256 sampler="DPM2 a Karras" {birds}"
It does create a image with prompt:  firetruck a Karras"        (including the " on end)
With sampler DPM2.

(I also added the schema.txt you requested to my old, closed, thread in case you still need / want it)

**Comment by gingivere0** [comment]
Oh I thought I fixed this with a previous update! I just pushed some new code that should solve this problem. Give it a shot and let me know how it goes.

If you're not having any other errors, I don't think I need the schema right now. I might if something else pops up though

**Comment by Darkflo264** [comment]
I just tried it with different samplers. It´s working very well now. Thank you and great job!

Greetings! (and closing this issue)
